version: '3.3'
services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123321
    ports:
      - 5432:5432
  nats-streaming:
    ports:
      - 4444:4222
      - 8223:8223
    image: nats-streaming
